const Topsales = [
    {
        id: "1",
        title: "Nike Air Low Premium",
        text: "MEN Running Shoes",
        rating: "5+",
        btn: "Buy Now",
        img: "https://i.ibb.co/bBgxmSk/594997-1000x1000-removebg-preview.png",
        price: "150",
        color: "from-sky-600 to-indigo-600",
        shadow: "shadow-lg shadow-blue-500",
    },
    {
        id: "2",
        title: "Nike Air Force Green",
        text: "MEN Running Shoes",
        rating: "5+",
        btn: "Buy Now",
        img: "https://i.ibb.co/vwKknFV/air-force-1-high-se-shoes-6b703-K-removebg-preview.png",
        price: "150",
        color: "from-green-500 to-emerald-500",
        shadow: "shadow-lg shadow-green-500",
    },
    {
        id: "3",
        title: "Nike Addapt BB Rose",
        text: "MEN Running Shoes",
        rating: "5+",
        btn: "Buy Now",
        img: "https://i.ibb.co/pnJgMNX/image-removebg-preview.png",
        price: "150",
        color: "from-red-500 to-rose-500",
        shadow: "shadow-lg shadow-rose-500",
    },
    {
        id: "4",
        title: "Nike Air Premium",
        text: "MEN Running Shoes",
        rating: "5+",
        btn: "Buy Now",
        img: "https://i.ibb.co/16f6Rhr/vaporfly-next-2-road-racing-shoes-D4nt-S0-removebg-preview.png",
        price: "150",
        color: "from-orange-500 to-amber-500",
        shadow: "shadow-lg shadow-orange-500",
    },
    {
        id: "5",
        title: "Nike Adapt BB Pro",
        text: "MEN Running Shoes",
        rating: "5+",
        btn: "Buy Now",
        img: "https://i.ibb.co/2YfSZFG/dunk-low-retro-shoe-66-RGq-F-removebg-preview.png",
        price: "150",
        color: "from-gray-900 to-yellow-500",
        shadow: "shadow-lg shadow-yellow-500",
    },
    {
        id: "6",
        title: "Air Jordan PR3",
        text: "MEN Running Shoes",
        rating: "5+",
        btn: "Buy Now",
        img: "https://i.ibb.co/bBgxmSk/594997-1000x1000-removebg-preview.png",
        price: "150",
        color: "from-blue-500 to-cyan-500",
        shadow: "shadow-lg shadow-cyan-500",
    },
    {
        id: "7",
        title: "Nike Multi Smart Shoe",
        text: "MEN Running Shoes",
        rating: "5+",
        btn: "Buy Now",
        img: "https://i.ibb.co/2YfSZFG/dunk-low-retro-shoe-66-RGq-F-removebg-preview.png",
        price: "150",
        color: "from-yellow-500 to-yellow-500",
        shadow: "shadow-lg shadow-yellow-500",
    },
    {
        id: "8",
        title: "Nike Jordan Air Max",
        text: "MEN Running Shoes",
        rating: "5+",
        btn: "Buy Now",
        img: "https://i.ibb.co/16f6Rhr/vaporfly-next-2-road-racing-shoes-D4nt-S0-removebg-preview.png",
        price: "150",
        color: "from-[#936550] to-orange-900",
        shadow: "shadow-lg shadow-orange-800",
    },
    {
        id: "9",
        title: "Nike Old Max-x",
        text: "MEN Running Shoes",
        rating: "5+",
        btn: "Buy Now",
        img: "https://i.ibb.co/bBgxmSk/594997-1000x1000-removebg-preview.png",
        price: "150",
        color: "from-indigo-700 to-indigo-700",
        shadow: "shadow-lg shadow-indigo-500",
    },
    {
        id: "10",
        title: "Nike Lime Jordan 11",
        text: "MEN Running Shoes",
        rating: "5+",
        btn: "Buy Now",
        img: "https://i.ibb.co/vwKknFV/air-force-1-high-se-shoes-6b703-K-removebg-preview.png",
        price: "150",
        color: "from-green-600 to-lime-500",
        shadow: "shadow-lg shadow-lime-500",
    },
    {
        id: "11",
        title: "Nike Air Black Max",
        text: "MEN Running Shoes",
        rating: "5+",
        btn: "Buy Now",
        img: "https://i.ibb.co/bBgxmSk/594997-1000x1000-removebg-preview.png",
        price: "150",
        color: "from-slate-900 to-black",
        shadow: "shadow-lg shadow-black",
    },
    {
        id: "12",
        title: "Nike Zoom Max",
        text: "MEN Running Shoes",
        rating: "5+",
        btn: "Buy Now",
        img: "https://i.ibb.co/bBgxmSk/594997-1000x1000-removebg-preview.png",
        price: "150",
        color: "from-blue-900 to-blue-500",
        shadow: "shadow-lg shadow-blue-500",
    },
];

export default Topsales;